### ISSUE TITLE
Uncaught Exception on Startup

### ISSUE THREAD

**Issue by caa1982** [horizon-games/remix-app#1]
I have the following error in the console on Startup

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: _electron.app.setAboutPanelOptions is not a function
    at Object.<anonymous> (/home/lascar/Desktop/remix-0.1.1/resources/app.asar/build/main.js:113:15)
    at __webpack_require__ (/home/lascar/Desktop/remix-0.1.1/resources/app.asar/build/main.js:20:30)
    at /home/lascar/Desktop/remix-0.1.1/resources/app.asar/build/main.js:63:18
    at Object.<anonymous> (/home/lascar/Desktop/remix-0.1.1/resources/app.asar/build/main.js:66:10)
    at Object.<anonymous> (/home/lascar/Desktop/remix-0.1.1/resources/app.asar/build/main.js:460:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

------------------------
System information:

Linux version 4.13.0-32-generic (buildd@lgw01-amd64-004) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5))

Linux Mint 18.3 Sylvia

**Comment by pkieltyka** [comment]
Fixed (and tested) in dcdf8b84ef9ecfd932207ba723cb80bf16ec6bd0

I'll be uploading a pre-built release of v0.1.2 in a few minutes. Thanks for the report.
